# Generated by Django 4.1.11 on 2023-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingitem',
            name='video',
            field=models.FileField(default='default_video.mp4', upload_to='media/videos/'),
        ),
    ]
